version: '3'

services:
  backend:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "80:3000"
    links:
      - "backend"